apiVersion: v2
name: welcome-app
description: A Helm chart for deploying a customizable welcome web application
type: application
version: 2.0.0
appVersion: "1.24-alpine"
keywords:
  - nginx
  - welcome
  - web
maintainers:
  - name: Our Name
    email: our.email@example.com
